### ISSUE TITLE
Run in Docker on Synology

### ISSUE THREAD

**Issue by forepj** [eggertec/lextend#1]
It would be great if you could run this app in Docker on a Synology NAS

**Comment by stefanegger** [comment]
Right now our development is focused on new features and hardware. Next week we release a lextend appliance with six generic physical inputs. There you can trigger up to six Sonos actions with 6-250V AC or DC impulses. Then everyone can use lextend with any existing doorbell button.

In the future we might go also in the other direction an make lextend more hardware independent. The most important thing is to make lextend easy to use with a simple setup.

Maybe this will be a Docker setup in the near future.
